# fly.toml app configuration file generated for controle-acesso-fly on 2025-08-26T14:29:56-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'controle-acesso-fly'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  # Altere 'stop' para 'false' para manter a máquina ativa
  auto_stop_machines = false 
  auto_start_machines = true
  # Altere 0 para 1 para garantir que uma máquina esteja sempre rodando
  min_machines_running = 1 
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
source="logs_volume"
destination="/usr/src/app/logs"